data_cfg:
  dataset_name: CCPG
  dataset_root: /data/CCPG/Released/CCPG-ratio-pkl
  dataset_partition: ./datasets/CCPG/CCPG.json
  data_in_use: [True, False]
  num_workers: 8
  remove_no_gallery: false
  test_dataset_name: CCPG

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: false
  restore_hint: 20000
  save_name: BiggerGait__SAM3DBody__Projection_Voxel_Based_Gaitbase_Share
  eval_func: evaluate_CCPG_part_based
  sampler:
    batch_shuffle: false
    batch_size: 8
    sample_type: all_ordered
    frames_all_limit: 250
  metric: euc
  transform:
    - type: BaseRgbTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  chunk_size: 8
  model: BiggerGait__SAM3DBody__Projection_Voxel_Based_Gaitbase_Share
  pretrained_lvm: pretrained_LVMs/sam-3d-body
  pretrained_mask_branch: BYPASS
  image_size: 256
  sils_size: 32
  source_dim: 1280
  num_FPN: 4
  debug_pca_vis: true
  debug_voxel_export: true

  layer_config:
    hook_mask:
      - False
      - False
      - False
      - False
      - False
      - False
      - False
      - False
      - False
      - False
      - False
      - False
      - False
      - False
      - False
      - False
      - True
      - True
      - True
      - True
      - True
      - True
      - True
      - True
      - True
      - True
      - True
      - True
      - True
      - True
      - True
      - True
    hook_sample_type: "chunk"

  num_unknown: 16

  ot_temperature: 0.01
  ot_dist_thresh: 0.2
  ot_iters: 8

  voxel_cfg:
    grid_size:
      - 64
      - 32
      - 32
    temporal_window: 3
    depth_center_mode: bbox_mid
    depth_center_offset: 0.0

  branch_configs:
    - use_apose: true
      yaw: 0.0

  Mask_Branch:
    source_dim: 1280
    target_dim: 2
    p: 0.
    softmax: true
    Relu: false
    Up: true

  backbone_cfg:
    type: ResNet9
    block: BasicBlock_Time
    in_channel: 16
    channels:
      - 64
      - 128
      - 256
      - 512
    layers:
      - 1
      - 1
      - 1
      - 1
    strides:
      - 1
      - 2
      - 1
      - 1
    maxpool: false
  SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 32
  SeparateBNNecks:
    class_num: 100
    in_channels: 256
    parts_num: 32
  bin_num:
    - 32

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 10000
    - 15000
  scheduler: MultiStepLR

trainer_cfg:
  find_unused_parameters: true
  enable_float16: true
  fix_BN: false
  log_iter: 100
  with_test: true
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 5000
  save_name: BiggerGait__SAM3DBody__Projection_Voxel_Based_Gaitbase_Share
  sync_BN: true
  total_iter: 20000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8
      - 4
    frames_num_fixed: 30
    frames_skip_num: 4
    frames_num_max: 40
    frames_num_min: 20
    sample_type: fixed_unordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: RandomHorizontalFlip
        - type: BaseRgbTransform
